site_name: native-kt
site_url: https://husker-dev.github.io/native-kt/
site_description: Gradle plugin for convenient C/C++ integration into a Kotlin Multiplatform project
site_author: Nikita Shtengauer
repo_url: https://github.com/husker-dev/native-kt
repo_name: husker-dev/native-kt

theme:
  name: material
  language: en
  palette:
    # Dark theme
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Dark theme
    # ТLight theme
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Light theme
  features:
    - navigation.tabs          # вкладки вверху
    - navigation.sections      # секции в боковом меню
    - navigation.expand        # автораскрытие меню
    - navigation.top           # кнопка "наверх"
    - search.highlight         # подсветка результатов поиска
    - search.suggest           # автодополнение в поиске
    - content.code.copy        # кнопка копирования кода

nav:
  - Main: index.md

markdown_extensions:
  - admonition              # красивые блоки Note/Warning/Tip
  - pymdownx.highlight      # подсветка синтаксиса
  - pymdownx.superfences    # вложенные блоки кода
  - pymdownx.tabbed:        # вкладки внутри страницы
      alternate_style: true
  - pymdownx.emoji:         # эмодзи
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true       # якорные ссылки у заголовков

plugins:
  - search:
      lang: en
