[project]
site_name = "native-kt"
site_url = "https://husker-dev.github.io/native-kt/"
site_description = "Gradle plugin for convenient C/C++ integration into a Kotlin Multiplatform project."
site_author = "Nikita Shtengauer"
repo_url = "https://github.com/husker-dev/native-kt"
repo_name = "husker-dev/native-kt"
nav = [
  {"Home" = "index.md"},
  {"About" = "about.md"}
]

# Default theme
[project.theme.palette]
scheme = "slate"

# Theme colors
[project.theme]
language = "en"
palette.primary = "deep purple"
palette.accent = "deep purple"
features = [
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.path",
    "toc.integrate"
]
